//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONING_App.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesBaza : DbContext
    {
        public EntitiesBaza()
            : base("name=EntitiesBaza")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gradovi> Gradovi { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<Korisnicki_racuni> Korisnicki_racuni { get; set; }
        public virtual DbSet<Odjeli> Odjeli { get; set; }
        public virtual DbSet<Poduzeca> Poduzeca { get; set; }
        public virtual DbSet<Vrste_korisnika> Vrste_korisnika { get; set; }
        public virtual DbSet<Godisnji_odmori> Godisnji_odmori { get; set; }
        public virtual DbSet<Materijali_i_sirovine> Materijali_i_sirovine { get; set; }
        public virtual DbSet<Mjerne_jedinice> Mjerne_jedinice { get; set; }
        public virtual DbSet<Poslovni_partneri> Poslovni_partneri { get; set; }
        public virtual DbSet<Proizvodi> Proizvodi { get; set; }
        public virtual DbSet<Slobodni_dani> Slobodni_dani { get; set; }
        public virtual DbSet<Vrste_partnera> Vrste_partnera { get; set; }
        public virtual DbSet<Zapisnici_skladista> Zapisnici_skladista { get; set; }
    }
}
