//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONING_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Godisnji_odmori
    {
        public int id { get; set; }
        public int korisnik { get; set; }
        public System.DateTime datumOd { get; set; }
        public System.DateTime datumDo { get; set; }
        public Nullable<int> odobrio { get; set; }
        public Nullable<bool> odobreno { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Korisnici Korisnici1 { get; set; }
    }
}
