//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONING_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materijali_i_sirovine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materijali_i_sirovine()
        {
            this.Zapisnici_skladista = new HashSet<Zapisnici_skladista>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public int mjernaJedinica { get; set; }
        public int kolicina { get; set; }
        public int poslovniPartner { get; set; }
        public string specifikacija { get; set; }
        public int poduzece { get; set; }
        public bool prikazi { get; set; }
    
        public virtual Mjerne_jedinice Mjerne_jedinice { get; set; }
        public virtual Poduzeca Poduzeca { get; set; }
        public virtual Poslovni_partneri Poslovni_partneri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapisnici_skladista> Zapisnici_skladista { get; set; }
    }
}
