//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONING_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poslovni_partneri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poslovni_partneri()
        {
            this.Materijali_i_sirovine = new HashSet<Materijali_i_sirovine>();
        }
    
        public int id { get; set; }
        public string imePoduzeca { get; set; }
        public string OIB { get; set; }
        public string imeDirektora { get; set; }
        public string prezimeDirektora { get; set; }
        public string kontaktBroj { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public int mjesto { get; set; }
        public int vrstePartnera { get; set; }
        public int poduzece { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materijali_i_sirovine> Materijali_i_sirovine { get; set; }
        public virtual Poduzeca Poduzeca { get; set; }
        public virtual Vrste_partnera Vrste_partnera { get; set; }
    }
}
