//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONING_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisnici_skladista
    {
        public int id { get; set; }
        public Nullable<int> proizvod { get; set; }
        public Nullable<int> materijal { get; set; }
        public int kolicina { get; set; }
        public Nullable<System.DateTime> datumVrijeme { get; set; }
        public bool izdano { get; set; }
        public int zabiljezio { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Materijali_i_sirovine Materijali_i_sirovine { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
