//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalkulatorGodisnjeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slobodni_dani
    {
        public int id { get; set; }
        public int korisnik { get; set; }
        public int slobodniDani { get; set; }
        public int iskoristeniDani { get; set; }
    }
}
