//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autentifikacija
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Korisnici
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Ime")]
        public string ime { get; set; }
        [DisplayName("Prezime")]
        public string prezime { get; set; }
        [DisplayName("OIB")]
        public string oib { get; set; }
        [DisplayName("E-mail")]
        public string email { get; set; }
        [DisplayName("Kontakt broj")]
        public string kontaktBroj { get; set; }
        [DisplayName("Adresa")]
        public string adresa { get; set; }
        [DisplayName("Mjesto")]
        public int prebivaliste { get; set; }
        [DisplayName("Uloga")]
        public int uloga { get; set; }
        [DisplayName("Šifra raèuna")]
        public int korisnickiRacun { get; set; }
        [DisplayName("Odjel")]
        public int odjel { get; set; }
        [DisplayName("Poduzeæe")]
        public Nullable<int> poduzece { get; set; }

        public virtual Korisnicki_racuni Korisnicki_racuni { get; set; }
    }
}
